# Generated by Django 5.0.4 on 2024-05-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polygons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="polygon",
            old_name="crosses_antrimeridian",
            new_name="crosses_antimeridian",
        ),
    ]
