version: '3.8'
services:
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      - POSTGRES_DB: webpolygon
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: test
  
  web:
    build: .
    command: gunicorn webpolygon.wsqi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL: postgres://postgres.test@db:5432/webpolygon
volumes:
  postgres_data:
