FROM python:3.8-slim

RUN apt-get update \
    && apt-get install -y g++
# Устанавливаем GDAL зависимости
RUN apt-get install -y binutils libproj-dev gdal-bin libgdal-dev
# Рабочая среда контейнера
WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV GDAL_LIBRARY_PATH /usr/lib/libgdal.so

# Открываем порт 8000
EXPOSE 8000

# Запуск приложения
CMD [ "gunicorn", "--bind", "0.0.0.0:8000", "webpolygon.wsgi:application" ]